### ISSUE TITLE
What layout does compan expects?

### ISSUE THREAD

**Issue by amirouche** [panicz/compan#1]
I am working for an interface for guildhall (http://guildhall.hypermove.net) and was wondering about your project. This seems neat.

What layout does compan expects to be able to use a given repository?

Is it possible to provide the branch or tag information to hg so that I fetch a particular revision of the project?

Tx!

**Comment by amirouche** [comment]
Are you interested in changing stuff in compan to make it useable also outside an REPL. I mean use it as the basis of the above website instead of guildhall?

guildhall has bugs I can not port it to guile 2.2. So I am considering using compan instead.

**Comment by amirouche** [comment]
Actually there is everything I need. I mean it seems like so.

What do you think about dependencies? How did you plan to handle that? Or is it already transitive as long as every package use (load-modules)?

**Comment by panicz** [comment]
My initial intent was to make this project as lightweight and decentralized as possible -- I thought that it should be sufficient to have a module in a repository, and that I wouldn't need to worry about the things that I usually need to worry about. But after a successful initial run, it turned out that under some circumstances it didn't work and I didn't have time to look exactly why.
So I can't exactly say whether (load-modules) behaves consistently with nested modules. Perhaps some tweak to the Guile module system is needed in order for that to work

**Comment by panicz** [comment]
More specifically, the problem arises when load-modules is used from the compiled code. I think that one would need to consult it with Andy Wingo, to figure out how to tackle this issue, i.e. delay the compilation until all the modules are fetched.

**Comment by amirouche** [comment]
Personal backlog clean-up.
